version: '3.8'

services:

    sample:
        image: jifloresp/cec-font:0.1
        container_name: sample
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:9000
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true    # docker run -i
        tty: true           # docker run -t